### ISSUE TITLE
CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config)

### ISSUE THREAD

**Issue by mog3n** [auth0/nextjs-auth0#1063]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi there,

Having issues deploying nextjs-auth0 to deployment on **Vercel**.

On the /callback phase, I'm receiving a 400 `ERROR	CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).`. This does not happen when I run the app in development mode on a local server.

I looked into the issue and it seems like it's similar to the `checks.state argument is missing` error found in an older API version. None of the solutions worked.

The app is set up using the exported name `handleAuth`. I followed the instructions on the Next.js docs, including the README on deploying a [sample app on Vercel](https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md), browsed the API docs to see if creating a custom auth0 instance would help, but was not able to find a solution.

We don't have a custom domain, so the base URL is set to https://my_app.vercel.app/
I am not using any development or preview deployments.

All env vars appear to be set correctly:
```
AUTH0_SECRET=
AUTH0_BASE_URL=https://my_app.vercel.app
AUTH0_ISSUER_BASE_URL=
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
AUTH0_SCOPE=openid email profile
AUTH0_AUDIENCE=
```

**The error from Vercel Function Logs**

```
[GET] /api/auth/callback?code=ABC&state=EFG

info  - Loaded env from /var/task/frontend/.env.production
2023-02-12T06:37:40.878Z	94461eef-0f3c-4191-81ce-1c1217fd93b0	ERROR	CallbackHandlerError: Callback handler failed. CAUSE: Missing state cookie from login request (check login URL, callback URL and cookie config).
    at CallbackHandlerError.AuthError [as constructor] (/var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:34:16)
    at CallbackHandlerError.HandlerError [as constructor] (/var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:110:23)
    at new CallbackHandlerError (/var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:138:28)
    at /var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:42:31
    at step (/var/task/frontend/node_modules/tslib/tslib.js:193:27)
    at Object.throw (/var/task/frontend/node_modules/tslib/tslib.js:174:57)
    at rejected (/var/task/frontend/node_modules/tslib/tslib.js:165:69) {
  code: 'ERR_CALLBACK_HANDLER_FAILURE',
  cause: MissingStateCookieError: Missing state cookie from login request (check login URL, callback URL and cookie config).
      at new MissingStateCookieError (/var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/auth0-session/utils/errors.js:39:16)
      at /var/task/frontend/node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:30:63
      at step (/var/task/frontend/node_modules/tslib/tslib.js:193:27)
      at Object.next (/var/task/frontend/node_modules/tslib/tslib.js:174:57)
      at fulfilled (/var/task/frontend/node_modules/tslib/tslib.js:164:62) {
    expose: true,
    statusCode: 400,
    status: 400
  },
  status: 400
}
```

Thanks! Let me know if I'm doing anything wrong.

### Reproduction

1. Deploy app on Vercel
3. Apply the environment variables specified in the docs. Use the preassigned production URL as the AUTH0_BASE_URL
4. Re-deploy site to apply new env vars
5. Visit Production site and sign in
6. Sign in with Google
7. User is redirected to /api/auth/callback with a HTTP 400 error

### SDK version

2.2.1

### Next.js version

13.1.6

### Node.js version

18.13.0

**Comment by mog3n** [comment]
Oops, issue was my `AUTH0_CLIENT_SECRET` was incorrect. Closing.

**Comment by IonelLupu** [comment]
@mog3n I get the same error but my `AUTH0_CLIENT_SECRET` is correct 😞 .  

I debugged this further and it wants a cookie called "state" which doesn't exist in the browser's cookies:
![image](https://github.com/auth0/nextjs-auth0/assets/4083652/67eb04cf-9564-47ee-93cd-c7be97f919d6)

**Comment by caaatisgood** [comment]
Hey @IonelLupu i'm facing the same issue. Everything configuration-wise seems correct. What version of this library are you using btw? I'm on `2.6.2` atm but I noticed the way the cookies are being retrieved is different in the latest version. I wonder if the issue will be solved just by upgrading the library.

**Comment by nguaman** [comment]
I am facing this same problem.
The environment variables are loading correctly.

![image](https://github.com/auth0/nextjs-auth0/assets/3330998/b848827c-2937-4f29-9807-ba383e76fc9c)

versions: 

```
nextjs-auth0 : ^3.1.0
Next.js v13.4.17
```

I think it has something to do with the Docker file. I use the one they have as an example in the repository.

source : https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

Since if I try it locally without creating the Docker, everything works correctly.

**Comment by nicosuave** [comment]
For those impacted, I've [opened a new issue](https://github.com/auth0/nextjs-auth0/issues/1377) for visibility

**Comment by nguaman** [comment]
I think I know why this was happening.

There was a bug that was fixed in Next.js v13.4.19 (https://github.com/vercel/next.js/pull/54203), which was causing environment variables not to be reflected in standalone mode.

So when I generated the Docker image, the AUTH0_BASE_URL variable was not taken into account when deploying on Google Cloud Run.

What value of AUTH0_BASE_URL was being used? It was using the value from the .env file that I had in development mode (AUTH0_BASE_URL=http://localhost:3000).

Therefore, what I did was create a .env.production file that had the AUTH0_BASE_URL set to the production value (AUTH0_BASE_URL=https://www.xxxx.net).

The "Missing state cookie from login request" issue, in my case, was because the AUTH0_BASE_URL didn't match the production version.

Then I tried it in incognito mode, and it worked correctly.

As I mentioned, this was my particular case, and I'm not sure if it's directly related to other cases.

**Comment by nicosuave** [comment]
Thanks @nguaman trying the update on may end hope that solves 🤞

I very much appreciate all the detail here; we've got a _freakishly_ similar infra setup. I even tried just committing my full .`env` locally, running next.js in dev mode on Cloud Run to no avail. Perhaps my printing of env vars was even deceptive if there was some `dotenv` lifecycle issue.

**Comment by nguaman** [comment]
What you could try is to forget about .env and env.local and generate .env.development and .env.production files.

This is because .env and .env.local take precedence over other .env.* files. 

If you are using the [Dockerfile provided in the repository's examples for Next.js](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile), it will default to env.production since the NODE_ENV variable is set to production. Therefore, it will use the .env.production file.

Try adding a console.log statement above handleAuth (as shown in the image). This way, you can see the value that AUTH0_BASE_URL is taking.

![image](https://github.com/auth0/nextjs-auth0/assets/3330998/99b862ce-894b-45b3-a65f-ba8834b56e09)

```
console.log('the AUTH0_SECRET env var is set: ', process.env.AUTH0_SECRET);
console.log('the NODE_ENV env var is set: ', process.env.NODE_ENV);
console.log('the AUTH0_CLIENT_ID env var is set: ', process.env.AUTH0_CLIENT_ID);
console.log('the AUTH0_CLIENT_SECRET env var is set: ', process.env.AUTH0_CLIENT_SECRET);
console.log('the AUTH0_BASE_URL env var is set: ', process.env.AUTH0_BASE_URL);
```

Another thing that was mixed up with this error, but I'm not sure if it's related, is that Docker wasn't running on Google Cloud Run because the HOSTNAME variable wasn't set to 0.0.0.0."

https://github.com/vercel/next.js/issues/54093#issuecomment-1685026425

Another detail is always to generate the Docker build with --no-cache.

Good luck!"

**Comment by dizzyjaguar** [comment]
Any updates on this? Currently facing this on a **Vercel** project with **auth0**

**Comment by pratsandboxwealth** [comment]
I would appreciate if there are any updates here. I too am facing the same issue in Vercel

**Comment by IonelLupu** [comment]
a small update here from us: we had custom auth handler where we did some API calls. These API calls failed and we didn't know about it until we debugged it for hours.. This is the reason we got the error: the auth handler threw an error

**Comment by mariale-mentaport** [comment]
We have the same issue, any updates on this issue?

**Comment by nicosuave** [comment]
I just moved off of Auth0 🤷‍♂️

**Comment by mariale-mentaport** [comment]
Where did u move to?

**Comment by nicosuave** [comment]
NextAuth.js is doing the trick

**Comment by PaulAtkins88** [comment]
same issue :( Would love an update
