### ISSUE TITLE
`handleProfile()` should return roles as well

### ISSUE THREAD

**Issue by corysimmons** [auth0/nextjs-auth0#110]
Right now it returns `"http://localhost:3000/role": "guest"` regardless of what roles the user actually has in the Auth0 application.

**Comment by katrinaywatson** [comment]
+1 would also love if roles were included in handleProfile(). Anyone come up with a solution for this yet?

**Comment by glenmcrae** [comment]
+1 this would be really useful

**Comment by corysimmons** [comment]
I haven't investigated for workarounds, but I'm using Okta with my company and their SDKs are kinda lacking so I realized I needed to just ignore SDKs and use these companies' REST APIs exclusively. I forget what I was trying to do here but there is probably a workaround involving some REST call.

**Comment by adamjmcgrath** [comment]
@corysimmons @glenmcrae @katrinaywatson @cmbirk `handleProfile` will return your ID Token's claims. In order to add roles to your ID Token claims, you'll need a custom rule in your tenant, see https://auth0.com/docs/authorization/sample-use-cases-rules-with-authorization#add-user-roles-to-tokens as an example

**Comment by tmokmss** [comment]
I found the more modern way to include Auth0 role data in an access token/id token is to use [Auth0 Action](https://auth0.com/docs/customize/actions/write-your-first-action). Add a custom action like below and set it in Login action.

https://community.auth0.com/t/how-to-add-roles-and-permissions-to-the-id-token-using-actions/84506
