### ISSUE TITLE
Intermittent Logout Failure with Custom Session Store

### ISSUE THREAD

**Issue by k-1ee** [auth0/nextjs-auth0#1531]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In the past, stateless sessions were problematic for logouts in our application due to the race condition between clearing the user agent's cookies & a concurrent network request that sets a valid cookie.

To solve this, we've implemented a custom session store using Redis (by following this [example](https://github.com/adamjmcgrath/nextjs-auth0-redis-session/blob/main/lib/auth0-config.ts)). As a result, the success rate of logouts have improved drastically -- _**however**_, I'm still noticing that logout will fail at times. This failure seems to happen at the application session layer since there is a "Successful Logout" log in our Auth0 tenant, but the application session is still active.

FWIW:
- logout failure occurs roughly every 1 in 10 attempts
- when logout fails, a subsequent logout seems to work fine

All that to say, I suspect there may be a race condition given the intermittent nature of the issue. Ideally, having stateful sessions should eliminate this issue. 

### Reproduction

1. Set up store with Redis (.get/set/delete methods)
2. Supply store as `config.session` to `initAuth0`
3. Invoke logout handler (`/api/auth/logout`)

### nextjs-auth0 version

2.6.3

### Next.js version

13.4.12

### Node.js version

18.18.2

**Comment by adamjmcgrath** [comment]
Hi @k-1ee - thanks for raising this

If you have lots of sets on the session store for the same key concurrently with your delete, I can imagine that you would still have concurrency issues - where a request may start before the logout request, but it's set to the store may happen after the logout's delete (and so re-establish the session)

The issue is quite well described in https://github.com/tj/connect-redis/issues/328 

The easiest solution would be to limit the number of set's to the store. This SDK writes to the store on every request, but you can configure it not to do this (by disabling [session.rolling](https://auth0.github.io/nextjs-auth0/interfaces/config.SessionConfig.html#rolling)) or you can configure it to roll the session more selectively (using [session.autoSave](https://auth0.github.io/nextjs-auth0/interfaces/config.SessionConfig.html#autoSave) = false and [touchSession](https://auth0.github.io/nextjs-auth0/types/session_touch_session.TouchSession.html))

I see in connect-redis that there was also an attempt to modify the store (using a slow delete) to prevent this https://github.com/tj/connect-redis/pull/333, but this was later reverted https://github.com/tj/connect-redis/pull/347

**Comment by k-1ee** [comment]
@adamjmcgrath - There definitely does seem to be a lot of sets taking place. I had a feeling that this may be the case -- appreciate the insight! 

I'll close this for now as your suggestions provide good direction into mitigating the issue.
