### ISSUE TITLE
Allow functions to return a result instead of writing to the response stream

### ISSUE THREAD

**Issue by jordie23** [auth0/nextjs-auth0#157]
### Describe the problem you'd like to have solved

Sometimes I'd like to be able to modify the response of the functions this library provides or at least take additional actions based on whatever the response is. I can't do either as the functions write directly to the response stream.

### Describe the ideal solution

Allow the ability to have the functions return an object rather than write to the stream. Maybe if the 'res' object is not passed in, then the functions could return their result. Perhaps in an object like:

```javascript
{
  status: 200,
  data: {
      key: "value"
  }
}
```

Then I can do whatever I want with it or based on it, and write to the response stream myself.

## Alternatives and current work-arounds

Performing what are probably duplicate checks before calling these functions.

**Comment by adamjmcgrath** [comment]
Hi @jordie23 - do you have any specific use cases you can share? I'm evaluating this feature for the Beta

**Comment by Naddiseo** [comment]
Adding my 2c since I have a similar usecase: for us, we have/want unified code in the client for handling responses from the server, eg, only one function that calls `fetch`, so that we can assume the interface/data structure between client and server is always the same shape. 
In our code we have the shape `{ ok: boolean, payload: any | Error }` to represent the data coming back from the server. However, for auth0 code we currently have to special case the response handling to check for HTTP status 401, and then check the data structure of the returned data.
Ideally, we could modify what auth0-nextjs will return so that, for example, the not_auth response returns `HTTP 200 ( {ok: false, payload: {error: "not_authorized} } )` and our client side code wouldn't have to be specialized.

**Comment by adamjmcgrath** [comment]
Hi @Naddiseo - this sounds like a different topic.

@jordie23 - wants the route handlers methods to return objects rather than act on the response instance.

It sounds like you want the `/api/me` api request to return 200 rather than 401 when the user is not authorised to visit the URL. I don't think this would be a good API design for us, so we're going to keep it the same and I'm afraid you'll have to handle the 401 for anonymous users

**Comment by Naddiseo** [comment]
@adamjmcgrath, not so; I want to modify the response from handleProfile/handleLogin to shape it to look like the rest of my API

**Comment by adamjmcgrath** [comment]
@Naddiseo what do you want to change about the `handleLogin` response?

**Comment by Naddiseo** [comment]
@adamjmcgrath, sorry, `handleLogin` was muscle memory. I with to be able to modify the response of `requireAuthentication` and `handleProfile`: I want to be able to control the shape of the data coming back to the client so that I don't have to special-case auth0 related responses.

**Comment by jordie23** [comment]
@adamjmcgrath The alternative would be to have more hooks/callbacks. Perhaps like you have for `onUserLoaded`. So allow async functions that can be run before or after the request is sent to auth0. 

As long as I can run code after the auth0 request is made but before the response is sent to the user that'd be perfect. (And the operation result (success/failure) and information is passed into the async function)

e.g. for all actions you could have a `beforeClientResponse` option that is called before `res` is acted on, and it'll have args that include whether the operation was a success, and any other returned/requested information like session information.

**Comment by adamjmcgrath** [comment]
Thanks for sharing that information @jordie23 

> I with to be able to modify the response of requireAuthentication and handleProfile

Regarding changing these responses - I don't expect we'll be interested in doing this. We have new frontend tooling in the Beta (https://github.com/auth0/nextjs-auth0/tree/beta) that rely on those responses and making them customisable would add a complexity and brittleness to the SDK that overrides the potential benefits.

That said - we do want the SDK to be extensible, so I'm happy to discuss more hooks than the ones we have already for `handleLogin` and `handleCallback` - if you have specific use cases for hooks in `handleLogout` for example, please raise a separate issue with your use case.

If you still want to modify the response from `handleProfile` and `requireAuthentication`, it would be trivial to create your own handlers, using public apis, to return whatever you want, eg

```js
export default function handleProfile(req, res) {
  const session = await auth0.getSession();
  if (!session?.user) {
    // whatever response you want
  } else {
    res.json(session.user);
  }
}
```

I'm going to close this issue, but happy to discuss more usecases for hooks.
