### ISSUE TITLE
nextjs-auth0 for CSR

### ISSUE THREAD

**Issue by gmwill934** [auth0/nextjs-auth0#178]
Hello

I’ve looked at the nextjs-auth0 sdk and the presented examples for authentication and authorization provided are for server side / api scenarios using sessions and cookies.

What about if I am using CSR with NextJS? (my app is a client server architecture, I have my own custom backend)

What would be the ‘correct’ sdk to use for authentication and authorization for nextjs using client side rendering?
(i.e generating tokens and protecting my pages, etc)

Thanks!

**Comment by rogelio-meza-t** [comment]
Hi @gmwill934 !!

You can use `getServerSideProps` in order to perform some tasks before the page is rendered.

If you want to protect a page, there are some examples out there (I think you already checked the examples). Also, you can call inside `getServerSideProps` something like `const session = await auth0.getSession(req);` and check if the session is present, if not, you can redirect to `/api/login`. to force the user to login again.

For security reasons, you cannot access the token on the client-side, but you can write  an api enpoint using NexJs and call your API as usual from there. There is an example of this specific use case.

Don't forget to implement in your API a custom authorizer to validate the token with Auth0.

In my case, I have all front-end with NextJS and a back-end with Flask.

**Comment by gmwill934** [comment]
Hey! @rogelio-meza-t 
`getServerSideProps` is for `SSR` which I don't want to use, I want to use Next JS as a full CSR (client side rendering) application.

**Comment by rogelio-meza-t** [comment]
Hi @gmwill934 
If you wants a full CSR why you choose NextJS? Why not just React?

As I said in the second paragraph, the purpose of `getServerSideProps` is to get the session/token after the page is rendered, because by default (and by security reasons) the session isn't accessible in the browser, then; if it exists render the page, if not, force the login.

Another approach could be writing a provider and then export wrapped components. Here, in this repository there is an example with this approach.

**Comment by gmwill934** [comment]
@rogelio-meza-t 
I choose it for their out of the box routing capabilities and automatic code splitting.

**Comment by Maxime-Fleurant** [comment]
because we want to use SSG capabilities

**Comment by MaxAst** [comment]
I would be interested in this approach as well. Would it be okay to just use this package in my custom backend and implement express routes that have the same functionality as the serverless functions in the next.js example?

**Comment by adamjmcgrath** [comment]
Hi @gmwill934 - thanks for raising this issue

If you want to use Next js as a SPA, you can use our `auth0-react` SDK. Take a look at the auth0-react Next.js example app here https://github.com/auth0/auth0-react/tree/master/examples/nextjs-app

Closing for now, update this thread if you want me to reopen it.
