### ISSUE TITLE
How to refetch a user

### ISSUE THREAD

**Issue by dohomi** [auth0/nextjs-auth0#182]
### Description

My app allows user to adjust the credentials of the user. Now I need to refetch the user credentials but refetch:true of 
```js
await auth0.handleProfile(req,res,{
refetch:true
})
```
does not update the user. How can I refetch the user that the new user roles are fetched? Currently only logout => login works which can't be the UX

### Reproduction

I followed the default setup and created an api endpoint which does not update the user:
```js
export default async function me(req: NextApiRequest, res: NextApiResponse) {
  try {
    await auth0.handleProfile(req, res, {
      refetch: true // only if on SSR
    })
  } catch (error) {
    res.status(error.status || 500).end(error.message)
  }
}
```
After calling `api/me` the user has still old `app_metadata`

**Comment by dohomi** [comment]
The only solution I found so far is using 
```
window.location.href = "/api/login" 
```
Not sure if thats intended to be the solution though.

**Comment by mosesoak** [comment]
@dohomi  You are correct that this library does not provide a solution for this important task. The other libs that work via the frontend have silent iframe reauth, this one does not since it's backend-only and uses a different flavor of auth.

We talked to this module's author and he told us that all auth0 modules are currently being rebuilt as a single core lib with extensions, so this particular lib won't be updated much from here on out. 

His proposed solution was that we could patch this library to update the cookie with new metadata after receiving a 200 from the PATCH. This would duplicate what is assumed to be on the server, not ideal, but could be generally kept in sync and considered reliable-enough. The idea would be to add a new method that updates the cookie in a similar way to the access token refresh method, that accepts arbitrary data to be written into the cookie (e.g. the changed metadata). This would be generally safe as it would only be called from the backend.

I do not know for sure that this would work. We didn't get around to attempting to write this PR. If you do, please post a PR and post a status to this issue, since we could really use it in our project!

**Comment by dohomi** [comment]
@mosesoak for now I will use the re-send the user to the login.

**Comment by adamjmcgrath** [comment]
Hi @dohomi - thanks for raising this

The new Beta will now update the stored session if it's updated, so if `auth0.handleProfile(req,res, { refetch:true })` returns user claims that are different to what is stored in the session, they will be updated.

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now. Please try it out, let me know if it's not working and I'll reopen this issue.
