### ISSUE TITLE
User Provider in the example doesn't exist

### ISSUE THREAD

**Issue by harshvitra** [auth0/nextjs-auth0#196]
### Description

In the example files both the typescript example and the basic example have a function to fetch user details. 
In this file we have a piece of code - 

```
export const UserProvider = ({ value, children }: UserProviderProps): ReactElement<UserContext> => {
  const { user } = value;

  // If the user was fetched in SSR add it to userState so we don't fetch it again
  React.useEffect(() => {
    if (!userState && user) {
      userState = user;
    }
  }, []);

  return <User.Provider value={value}>{children}</User.Provider>;
};
```

Since the User doesn't exist this leads to an error. 

<img width="641" alt="Screenshot 2020-11-21 at 1 16 35 AM" src="https://user-images.githubusercontent.com/25605193/99843341-6cc77880-2b97-11eb-998c-de1d2f0a9547.png">

### Environment

** Please provide the following:**

- Using the latest version of nextjs-auth0
- Next JS - typescript example

**Comment by glenmcrae** [comment]
User is the context in this example right? It needs to be declared above. 

`const User = React.createContext({ user: null, loading: false });`

**Comment by adamjmcgrath** [comment]
Hi @harshvitra  - thanks for raising this

> Since the User doesn't exist this leads to an error.

In the typescript and basic example the `User` is declared at https://github.com/auth0/nextjs-auth0/blob/master/examples/typescript-example/lib/user.tsx#L32 and https://github.com/auth0/nextjs-auth0/blob/master/examples/basic-example/lib/user.js#L7https://github.com/auth0/nextjs-auth0/blob/master/examples/basic-example/lib/user.js#L7 respectively.

From your screenshot it look like your file `src/utils/auth0/user.ts` has a `Syntax error`, probably because it's using `jsx`. If you change the file name from `user.ts` -> `user.tsx` - this should fix your syntax error.

**Comment by adamjmcgrath** [comment]
Hi @harshvitra - That should resolve your problem, so closing this issue for now, let me know if you want me to reopen it
