### ISSUE TITLE
Backing out of the Login page

### ISSUE THREAD

**Issue by treykaws** [auth0/nextjs-auth0#215]
### Description
I noticed a small bug (or may not be) when cloning the official example setup leveraging this package. The repo is [here](https://github.com/vercel/next.js/tree/canary/examples/auth0). The issue is with inconsistent state when returning back to the application without entering credentials on the auth0 hosted login page.

### Reproduction
To reproduce this issue simply clone the repo provided above and insert your auth0 application credentials. Login to the application, then logout of the application. Proceed to logging in again and instead of entering your credentials, just press the `Back` button in your browser. It will show the application in a state of being Logged in. But once you refresh the browser it will no longer be logged in. I wasn't sure if this was an error with the setup/configuration that I am using but wanted to see if anyone else was experiencing this.

**Comment by adamjmcgrath** [comment]
Hi @treykaws - thanks for raising this

This issue has been fixed in the Beta, by adding cache headers to the `/me` handler https://github.com/auth0/nextjs-auth0/blob/beta/src/handlers/profile.ts#L73

You can check out the Beta here https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0

Closing for now, feel free to reopen if you want to discuss further.
