### ISSUE TITLE
How do we customize the ReturnTo URL so that it takes the user to the same page where they were?

### ISSUE THREAD

**Issue by dredshep** [auth0/nextjs-auth0#283]
Hello. I am using NextJS-Auth0 beta. I see that there are options such as [these](https://github.com/auth0/nextjs-auth0/blob/master/src/handlers/logout.ts) where some settings could be picked somehow. I couldn't find anything in the documentation.

But, as far as I understand it, I would have to make a custom handler for it to do that? I don't know much about this. Perhaps there is a way to set it, such as directing to /api/auth/logout?returnTo=someUrl ? As it is now, Auth0 redirects to /, even after login or sign up. This is a bit bothersome for the client. I wish this library had a way to easily deal with this problem. Please clarify if it already exists.

I'm sorry that I post this as a type Feature Request, but there is no type Question for an issue in the selector.

**Comment by adamjmcgrath** [comment]
Hi @dredshep - dynamically redirecting users to the page they were on after `logout` is not offered with the SDK.

We can't do the same that we do with `returnTo` and `login`, because after logout the user is anonymous, so we can't trust any after logout appstate.

My suggestion would be (providing you don't have many urls to return to after logout), to register all the logout urls as `Allowed Logout URLs ` (see https://auth0.com/docs/logout/redirect-users-after-logout). Then create a custom logout handler that picks up the `returnTo` parameter and calls the logout handler with it.

Just be aware that if the returnTo url is not registered the user will get an error from Auth0 when they try to logout. Also, we don't offer local logouts that would perform the redirect without logging you out of Auth0, but if we did - you'd also need to sanitise the `returnTo` param, so your logout endpoint didn't become an open redirect.

eg.

```js
// pages/api/auth/[...auth0].js
import { handleAuth, handleLogout } from '@auth0/nextjs-auth0';

export default handleAuth({
  async logout(req, res) {
    // You don't strictly need to sanitise `req.query.returnTo` because it has to be in Auth0's "Allowed Logout URLs"
    // But if you ever added a local logout option you should sanitise it, like we do with the login `returnTo`
    // eg https://github.com/auth0/nextjs-auth0/blob/beta/src/handlers/login.ts#L70-L72
    const returnTo = req.query.returnTo;
    try {
      await handleLogout(req, res, {
        returnTo
      });
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  }
});
```
