### ISSUE TITLE
"checks.state argument is missing" in Safari

### ISSUE THREAD

**Issue by aaronbdixon** [auth0/nextjs-auth0#311]
Next 10.0.7
nextjs-auth0 1.1.0

Everything works as expected on every browser except Safari. In Safari I am getting "checks.state argument is missing" on the api/auth/callback url. This happens on localhost as well as hosted on vercel.

**Comment by adamjmcgrath** [comment]
Hi @aaronbdixon - thanks for raising this.

I'm not able to reproduce your issue using Safari 14.0.3 (16610.4.3.1.4)

it sounds like Safari is blocking the `state` cookie, so that when you return from the authorization server it can't be read. This is usually when the cookie's SameSite=Strict

Do you have any special cookie config set (or `legacySameSite` config set) - or do you have any custom security settings on your Safari?

**Comment by aaronbdixon** [comment]
I’m using the default settings for the auth0 library as described in the docs. I’m having this issue on all iOS browsers (assuming this is because off browsers are Safari under the hood in iOS) as well as Safari on my MacBook.

I didn’t have this issue when using a pre 1.0 version of the library. This began happening when I upgraded this week. I see the code and state params in the query string as well.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adamjmcgrath** [comment]
@aaronbdixon are you able to share the code for your app, or a simple app that reproduces the issue? Or can you share a link to your ruinning application?

**Comment by aaronbdixon** [comment]
I spun up a sample project and also wasn't able to reproduce. That led me to clear history / cache for both my app and for auth0 and everything started working in Safari again. Wondering if something got crossed up in the upgrade from pre 1.0. Anyways looks like that worked. Thanks for the great library.
