### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by gunar** [auth0/nextjs-auth0#326]
Your `v1` is amazing. Super well integrated into next.js, and provides all hooks and helpers I've been longing for (`handleAuth`, `withPageAuthRequired`, `withApiAuthRequired`). Thank you!

![you did it](https://i.giphy.com/media/bKBM7H63PIykM/giphy.gif)

**Comment by adamjmcgrath** [comment]
Thanks @gunar!

**Comment by Widcket** [comment]
Thanks!

**Comment by mustafaKamal-fe** [comment]
Same Here 
Great Work 
Final note, the generated docs needs a bit more polishing work

Thank you so much guys

**Comment by adamjmcgrath** [comment]
Thanks @mustafaKamal-fe! - feel free to open another issue if you have any specific suggestions about how ew can improve the generated docs

**Comment by verekia** [comment]
Glad this issue exists, because this is one of those projects that is actually game-changing and deserves and warm thank you. Auth is complicated, but having to manage both SSR and CSR gives even more headaches. I was not using Auth0, but I am now coming back to it because you've managed to make it so simple for us to use. Congrats and thank you very much.

**Comment by adamjmcgrath** [comment]
I love this issue! Thanks @verekia!
