### ISSUE TITLE
Passwordless email link authentication is not working

### ISSUE THREAD

**Issue by benhamiltonpro** [auth0/nextjs-auth0#346]
### Description

Passwordless email link authentication is not working.

### Reproduction

1. Created Auth0 SPA Application
2. Set the allowed callback URL to `http://localhost:3000/api/auth/callback`
3. Set allowed logout URL to `http://localhost:3000/`
4. Configured our nextjs application, including env vars, to use nextjs-auth0 default setup for `/pages/api/auth/[...auth0].js`
    ```
    import { handleAuth } from '@auth0/nextjs-auth0';
    
    export default handleAuth();
    ```
5. Went to the auth0 management dashboard
6. Navigated to the Passwordless Connection for email and opened the modal
7. Click the applications tab
8. Make sure the newly created SPA application from step 1 was checked
9. Clicked on try tab in modal
10. Selected application created earlier in step 1
11. Changed email recipient to my test email
12. Changed mode to `link`
13. Clicked Try
14. Clicked link in email

Obviously, the repeatable steps are 9-14. Which I expected to be authenticated into the nextjs application without issue. However, I get the following error 

`Cannot read property 'toString' of undefined`

This happens because the decodeState function for the get-login-state hook tries decoding a state that is undefined. The transientcookiehandler goes to read a cookie called state with the following function `transientCookieHandler.read('state', req, res)`.

While actually debugging the only set cookies that it claims are there from the request are session cookies. When I check the callback request in chrome dev tools network tab I see the state cookie listed under request cookies. The response cookies for that callback request have a state cookie with an empty value.

Any assistance is appreciated.

### Environment

> Please provide the following:

- **Version of this library used: 1.1.0
- **Version of the platform or framework used, if applicable: nextjs 10.0.7
- **Other relevant versions (language, server software, OS, browser): using `js` in VS Code with Chrome browser
- **Other modules/plugins/libraries that might be involved: N/A

**Comment by adamjmcgrath** [comment]
Hey @benhamiltonpro - thanks for raising this

First off - that's a bad error, apologies, it should say something like "Missing state cookie / missing code/state params", I'll raise some work internally to fix.

Secondly, I wouldn't expect the "Try" link to be able to complete login - I think that button is designed more to just test what the email will look like. 

In order to login, passwordless or otherwise, the login has to be initiated from the application. When you start login in your Next.js application (by visiting /api/auth/login) the SDK will leave a `state` cookie, which it will then verify using the `state` parameter from the callback url when the user is returned to your app (That's why the `transientCookieHandler` couldn;t find the `state` cookie). If you test Passwordless by logging in through the application, it should work fine.

> Created Auth0 SPA Application

Also, you need to create a "Regular Web Application", the authentication is handled serverside so this is not an SPA app in terms of login.

**Comment by benhamiltonpro** [comment]
Thank you for the quick response and the detailed explanation. I will first look at switching the app to a Regular Web Application instead of SPA.

So there is no way to send a magic link to a user with a verified email via the auth0 management API (say with an automated job) and have them click that link to get into the app? They have to first come to the app, hit the passwordless lock, and enter their email to get a link that will have the state?

**Comment by adamjmcgrath** [comment]
Hi @benhamiltonpro

> So there is no way to send a magic link to a user with a verified email via the auth0 management API (say with an automated job) and have them click that link to get into the app? 

You can do this with embedded passwordless login, see how this works [for SPAs](https://auth0.com/docs/connections/passwordless/guides/embedded-login-spa) (Using Auth0.js and Lock.js) and [for Web Apps](https://auth0.com/docs/connections/passwordless/guides/embedded-login-webapps) (we don't have an SDK for this, you'd use the node-auth0 client)

This SDK uses Universal Login, which is the preferred way to implement Passwordless Authentication because of the [security implications](https://auth0.com/docs/universal-login/universal-vs-embedded-login) of embedded auth.

To get approximately the flow you want for this SDK and Universal Login, you would do:

- configure the universal login to use passwordless https://auth0.com/docs/connections/passwordless/guides/universal-login
- prompt user to visit a page on your app that requires login (use `withPageAuthRequired` or `/api/auth/login`)
- They will visit the Universal Login Page and do the Passwordless flow, either code or link
- They'll be sent back to your app (where there will be a `state` cookie for the SDK to verify against the callback request)

**Comment by benhamiltonpro** [comment]
Got passwordless to work when starting the auth from our app. Thanks.

**Comment by jaredgalanis** [comment]
@adamjmcgrath, we are using the auth0 authentication api to generate a magic link and would like to allow it to log users into our nextjs app. The email link generation is successful, but when clicking the link in the email we are seeing this error in the browser: `state missing from the response`. 

We have configured universal login to use passwordless.

Currently, the link is generated from postman (so outside of the application), but we've also attempted to send it via server side or from the next.js client side, but nothing has had an effect on the outcome. Optimally we would trigger the generation of the email link from outside of our nextjs application entirely, is this possible?

**Comment by jaredgalanis** [comment]
I'm noticing that when we click on the magic link that we're getting redirected to the callback url with a `#` in the url where I'd expect a `?` where query params start. 

If I manually replace the `#` with a `?` and instead I get a state mismatch error. 

If I manually edit the state to match I get a `TypeError: id_token not present in TokenSet` error message.

**Comment by jaredgalanis** [comment]
Okay so I've been able to successfully login using a magic link I generate via the authentication api by using the state generated by the library. 

However, this involved me just copying and pasting into my api request the state from the browser URL that exists once the library redirects back to the auth0 universal login page. 

I would like to programmatically obtain this state and use it to automatically hit the authentication api to generate a magic link. All of the state generation occurs within the library and a redirect will happen before I'm able to obtain this state.

Is there a way to pre generate and set this state to a value that I pass to the library?

**Comment by jaredgalanis** [comment]
So to be more specific, the state that works for me appears to be generated with the nonce that is created by the login handler in the auth0/nextjs library, but it's generated when that handler redirects to the authorize endpoint at the auth0 domain.

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis 

> That said, we have configured universal login to use passwordless, but, optimally we would trigger the generation of the email link from outside of our nextjs application entirely, if this is possible

In order to login using this SDK, the login must start from the application.

Have a look at my suggestion in https://github.com/auth0/nextjs-auth0/issues/346#issuecomment-805855526 for how to approximate the flow you are trying to achieve using this SDK

**Comment by jaredgalanis** [comment]
Thanks @adamjmcgrath! 

I was starting to get that this is what you meant in your comments above. We are currently trying to see if we can devise a solution where the user hits the application which redirects to universal login page and to send the state query param that is generated for that page to an api that we control which generates the link. 

So far I have been successful in doing that, but I can't also know the email address since the the authorization URL that the callback handler in this library redirects us to seems to go through a series of redirects.

Are you aware of a way for the universal login page to receive params coming from the application? If could do this we could either generate the link ourselves automatically or we could at least fill in the email field on the passwordless lock page automatically.

Also, there doesn't seem to be documentation about having embedded password approaches work with auth0/nextjs. Am I missing something?

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis,

> We are currently trying to see if we can devise a solution where the user hits the application which redirects to universal login page and to send the state query param that is generated for that page to an api that we control which generates the link.

If you visit the Passwordless Universal Login page confgured for email, the user will be prompted to enter their email (which you can prefill if you know the email - see `custom_param` in the next comment) - to which, Auth0 will send a passwordless link, see https://auth0.com/docs/universal-login/configure-universal-login-with-passwordless#universal-login-lock-passwordless-

> Are you aware of a way for the universal login page to receive params coming from the application? 

Yep - there's an example here https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior (see the `custom_param` bit)

> Also, there doesn't seem to be documentation about having embedded password approaches work with auth0/nextjs. Am I missing something?

This is intentional, nextjs-auth0 only support the Universal Login Page

**Comment by jaredgalanis** [comment]
Thanks @adamjmcgrath! I think we're almost there after your help. 

One last thing I'm trying to figure out is how to get the current version of the sdk to provide an access token that is a jwt and not opaque. In past versions of the sdk I was able to pass an audience parameter to the config for the sdk's client, but this doesn't seem to be valid in the new version of the sdk.

**Comment by adamjmcgrath** [comment]
Hi @jaredgalanis - you should be able to pass the `audience` in the [authorizationParams](https://auth0.github.io/nextjs-auth0/interfaces/config.baseconfig.html#authorizationparams) config, in the [handleLogin options](https://auth0.github.io/nextjs-auth0/interfaces/handlers_login.loginoptions.html#authorizationparams) or use the `AUTH0_AUDIENCE` [environment variable](https://auth0.github.io/nextjs-auth0/modules/config.html#optional).

See the [Access an External API from an API Route Example](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#access-an-external-api-from-an-api-route) for more info

**Comment by jaredgalanis** [comment]
@adamjmcgrath is there a way to pass params to the `passwordless/start` endpoint that would be available in a pre or post registration hook or a rule to be able to set them as metadata for a user?

**Comment by adamjmcgrath** [comment]
@jaredgalanis - I don't know to be honest. That's probably one for the [community forums](https://community.auth0.com/)

**Comment by jaredgalanis** [comment]
> @jaredgalanis - I don't know to be honest. That's probably one for the [community forums](https://community.auth0.com/)

Thanks, @adamjmcgrath.

Leaving this here just in case someone else lands here. I had [found this](https://community.auth0.com/t/pre-registration-hook-not-running-when-creating-a-passwordless-user/50968/14) on the community forums last week after I pinged you here. It sounds like as of today's date, the answer is that hooks/rules aren't available in the passwordless flow.

That being said, we did find a way to engineer a solution without them. Thanks for all your help!!!

**Comment by thinkjrs** [comment]
In case a search finds someone here maybe this will help:

I experienced this recently and had nothing to do with this lib. I followed the in-dashboard setup instructions and could not get login to work, giving me the error the OP referenced. 

It turns out that I was using (old) custom HTML for my login page in the dashboard which was not compatible with the passwordless setup. 

I simply reset with the default HTML for passwordless and was able to further customize from there, to get everything working.

**Comment by willtpwise** [comment]
Definitely a big documentation gap here Auth0. Just wasted days fluffing around with passwordless auth and the next.js-auth0 sdk. Definitely considering Cognito now.

**Comment by stopyransky** [comment]
Perhaps this will help someone: 

I learned that the password-less 'magic' link created on user signup (I created it via `node-auth0` package managementApi.createUser) will redirect to url specified in "Allowed Callback URLs". 

As @jaredgalanis  mentioned above if we switch # with ? then it will recognise the params in the uri.

The login flow will work just fine however, if we change url from `/callback?` to `/login?`

By doing this I was able to login user. 

Question is: how to make a custom callback with `nextjs-auth0` to redirect to `/login` when landing on `/callback` from a password-less link? 

I still want to define /callback as I support login with password. How to do it? There are tonnes of docs in auth0.com available and yet it is very hard to find useful information. Perhaps some higher level overviews like descriptions of user workflows  with different options would work...

Another thing i found is that there are first-party apps and third-party apps and the first-party apps are treated as third-party on localhost... Few hours wasted on looking of how to enable app to be first-party due to this...

**Comment by mustafaTokmak** [comment]
> 

This comment was very useful for me, thank you so much

**Comment by mustafaTokmak** [comment]
> Perhaps this will help someone:
> 
> I learned that the password-less 'magic' link created on user signup (I created it via `node-auth0` package managementApi.createUser) will redirect to url specified in "Allowed Callback URLs".
> 
> As @jaredgalanis mentioned above if we switch # with ? then it will recognise the params in the uri.
> 
> The login flow will work just fine however, if we change url from `/api/auth/callback?` to `/api/auth/login?`
> 
> By doing this I was able to login user.
> 
> if you set "Allowed Callback URLs" in Auth0 Dashboard to accept both {root_url}/api/auth/callback (for flow with password) and guarded {root_url}/callback (for password-less), then the password-less flow will work - assuming that you have a generic guardian component that redirects to /api/auth/login if user/session is not present.
> 
> It is important to distinguish between a /api/auth/callback (server-side api in next.js for managing auth flow) and /callback which is a frontend component where user lands after clicking the email link...


This comment was very useful for me, thank you so much
