### ISSUE TITLE
Fetch data when using withPageAuthRequired()

### ISSUE THREAD

**Issue by pasenidis** [auth0/nextjs-auth0#368]
Hello, I don't quite understand the documentation and I have a question.
I want to combine the `withPageAuthRequired()` function provided from the SDK with my own so I can fetch some data with Axios with SSR.

How do I do that?
Currently I am doing this:
```js
const Create = () => {
 // code
};

export default Create;
export const getServerSideProps = withPageAuthRequired();
```

**Comment by flatsteve** [comment]
Hi there, after following along with the Auth0 tutorials on YouTube I came to a similar question. I understand that this SDK has undergone a major update since the tutorials were made but it leaves things a little confused (at least for me).

Regarding the above question, I was able to piece things together from looking at the docs and the migration guide to come up with the following...

    export const getServerSideProps = withPageAuthRequired({
        getServerSideProps: async ({ req, res }) => {
            const { user } = getSession(req, res);
            const posts = // code that fetchs users posts from DB // 
            
            return { props: { posts } };
        },
    });
    
This totally works but it left me feeling I had got something wrong by using `withPageAuthRequired` and `getSession` together. Is this a viable way to do things when you want the functionality `withPageAuthRequired` provides (e.g redirect) but you also need to make use of the user in `getServerSideProps`?

Thanks for your time and effort in making this SDK 👍

**Comment by pasenidis** [comment]
Hey, thank you for responding. That explains a lot to me.

**Comment by adamjmcgrath** [comment]
Thanks @pasenidis 

@flatsteve 

> This totally works but it left me feeling I had got something wrong by using withPageAuthRequired and getSession together. Is this a viable way to do things when you want the functionality withPageAuthRequired provides (e.g redirect) but you also need to make use of the user in getServerSideProps?

Yep - this is the way :) `getSession` is just looking up a key on a map, so it's v cheap

**Comment by flatsteve** [comment]
@adamauth Perfecto, thank you for your time and explanation 👍
