### ISSUE TITLE
When using `useUser` I get a 401 error, but I just want to know if they're logged in

### ISSUE THREAD

**Issue by flapjackfritz** [auth0/nextjs-auth0#430]
When I do `useUser` in my navbar, I get a 401 error when it calls `/api/auth/me`.

I just want to put the username in the navbar when the user is logged in, and not put it there when they're not logged in. Is there some way of doing this without getting a 401 error in my console? Am I using `useUser` incorrectly?

**Comment by Widcket** [comment]
Hi @flapjackfritz, thanks for raising this. That is expected behavior; the `useUser` hook [calls](https://github.com/auth0/nextjs-auth0/blob/main/src/frontend/use-user.tsx#L143) the SDK's provided profile route (`/api/auth/me` by default) and when not logged in the handler [fails](https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/profile.ts#L47) with a 401 status.

If you'd really like to get rid of the console log, you could set up [your own profile handler](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior) that returns a non-error status with a non-JSON body when the user is not logged in (so `useUser` fails to `.json()` the response and produces an error), e.g:
```js
try {
    const session = getSession(req, res);
    if (session) {
        await handleProfile(req, res);
    } else {
        res.status(200).end('No session'); // Non-JSON res body
    }
} catch (error) {
    // handle error
}
```

**Comment by clement-faure** [comment]
Hi @Widcket,

When using useUser without event a session token in cookie, i would expect for the /api/auth/me to not even be called. It is possible to override the default useUser behaviour without reimplementing it all ?

https://github.com/auth0/nextjs-auth0/blob/6996e25/src/frontend/use-user.tsx#L110

```
  const checkSession = useCallback(async (): Promise<void> => {
    try {
     const hasSessionToken = !!getSessionToken();
     if (!hasSessionToken) throw new Error();

      const response = await fetch(profileUrl);
      const user = response.ok ? await response.json() : undefined;
      setState((previous) => ({ ...previous, user, error: undefined }));
    } catch (_e) {
      const error = new Error(`The request to ${profileUrl} failed`);
      setState((previous) => ({ ...previous, user: undefined, error }));
    }
  }, [profileUrl]);
```

**Comment by Widcket** [comment]
Hi @clement-faure the session cookie is `HttpOnly` so it's not accessible from client-side JS. Therefore `useUser` needs to call the profile endpoint to fetch the profile, and the endpoint will send back a response with a `401` status code when the user is not logged in. So I'm afraid it's not possible to check the session from the client without hitting the profile endpoint.

**Comment by clement-faure** [comment]
> Hi @clement-faure the session cookie is `HttpOnly` so it's not accessible from client-side JS. Therefore `useUser` needs to call the profile endpoint to fetch the profile, and the endpoint will send back a response with a `401` status code when the user is not logged in. So I'm afraid it's not possible to check the session from the client without hitting the profile endpoint.

Well noted, thank you for your quick response !

**Comment by sKopheK** [comment]
have troubles making it work in nextJs v15 and nextjs-auth0 v4, handler does not seem to catch up, documentation does not list `auth/profile` in URLs to intercept in middleware
