### ISSUE TITLE
Add ability to send user directly to signup page on login

### ISSUE THREAD

**Issue by jonkcinema** [auth0/nextjs-auth0#471]
### Describe the problem you'd like to have solved

Most webapps have some sort of "create account" button.  The auth0-react library supports this via the screen_hint parameter:

`loginWithRedirect({ screen_hint: 'signup' })`

The nextjs-auth0 library does not appear to support this.

### Describe the ideal solution

Please add a way to send the user directly to the signup page.

E.g. `<a href="/api/auth/login?screenHint=signup">Sign up</a>`

## Alternatives and current work-arounds

You can create your own signup handler (e.g. pages/api/signup.js), but that seems pretty unfortunate given how simple and common of an operation this is.

**Comment by adamjmcgrath** [comment]
Hi @jonkcinema - thanks for raising this

How you do signup depends on which Universal Login Page you are using see https://community.auth0.com/t/how-do-i-redirect-users-directly-to-the-hosted-signup-page/42520 for more information

Because there are different APIs for the new Universal Login experience and the Classic one (there is actually no specific API for the classic experience), and there is no way for the SDK to know which Login experience your tenant is set to - it's not possible to provide a `signup` api in the SDK. You'll need to create one yourself as you've described in the workaround.

**Comment by jonkcinema** [comment]
Then why does the auth0-react library make it so easy?  It seems like it
would be an improvement to at least make the more common / simpler approach
supported, or at a minimum, improve the documentation so I could figure
this out without having to read through GitHub issues.  It seems like
enough people are struggling with this that the status quo isn’t ideal.

**Comment by adamjmcgrath** [comment]
Hi @jonkcinema 

The implimentation of `auth0-react` and this SDK are very similar and they both have the same constraints regarding the Classic and New Universal Login Pages:

```js
// auth0-react
loginWithRedirect({ screen_hint: 'signup' })

// nextjs-auth0
handleLogin(req, res, { authorizationParams: { screen_hint: 'signup' }});
```

**Comment by jonkcinema** [comment]
My point is, figuring this out was a pain.  It would be nice if you guys
made it easier.  At a minimum, through better documentation, and ideally
with a slight API modification like I suggested.  The auth0-react library,
which you say is very similar, supports this with just the addition of the
screen hint param.  Why does the nextjs lib require me to write a custom
handler?  Why can’t I just pass a screen hint param somewhere?

Anyway, my point is, your service is really great, but this is the one
thing that felt much harder to do than it should be.  And based on the
GitHub issues, I’m not the only one getting stuck with this.

Thank you for your quick responses,
-Jon
