### ISSUE TITLE
Enable the use of returnTo params in the logout endpoint.

### ISSUE THREAD

**Issue by aiji42** [auth0/nextjs-auth0#532]
### Describe the problem you'd like to have solved
The endpoint for login (/api/auth/login) allows the use of the `?returnTo=` parameter, but the endpoint for logout is ignored even if the same is given.  
The `interface LogoutOptions` has a `returnTo` property, so we can control where to redirect after logout. However, to do that, you have to define `logout.js` separately from `[...auth0.js]`.

### Describe the ideal solution
Make it possible to receive `returnTo` as a URL parameter when logout only by setting the endpoint with `handleAuth` (`[...auth0].js`).  
If a user logs out with `/api/auth/logout?returnTo=/top`, the user will be redirected to `/top`.

## Alternatives and current work-arounds

Currently, I define a separate endpoint for logout as below.

![スクリーンショット 2021-11-07 午後0 09 56](https://user-images.githubusercontent.com/6711766/140631033-98a68136-4389-42b0-b981-7c64a89d0678.png)

```ts
import { handleLogout } from '@auth0/nextjs-auth0'
import { NextApiHandler } from 'next'

const handler: NextApiHandler = (req, res) => {
  const { returnTo } = req.query
  return handleLogout(req, res, {
    returnTo: Array.isArray(returnTo) ? returnTo[0] : returnTo
  })
}

export default handler
```

**Comment by adamjmcgrath** [comment]
Thanks for raising this @aiji42 - Going to close, see my comment https://github.com/auth0/nextjs-auth0/pull/533#event-5598796393

**Comment by aiji42** [comment]
@adamjmcgrath Thanks for the reaction.
I understand your idea. However, I think there is room for improvement in having to separate `[...auth0].js` and `logout.js` to specify `returnTo`.
I think it would be useful to be able to specify that with `handleAuth` arguments or environment variables. Please let me know what you think.

**Comment by adamjmcgrath** [comment]
> I think it would be useful to be able to specify that with handleAuth arguments or environment variables.

Hi @aiji42 - you can already specify it as an environment variable using `AUTH0_POST_LOGOUT_REDIRECT` see https://auth0.github.io/nextjs-auth0/interfaces/config.baseconfig.html#routes

**Comment by aiji42** [comment]
@adamjmcgrath
Oh, I see! I had overlooked the documentation. Thank you very much for your help.

**Comment by dr-skot** [comment]
I know this is closed but I'd like to upvote this feature request.

Auth0's docs advertise a `logout?returnTo=` parameter, which makes it surprising when `[...auth0].js` turns out not to support it.

[Redirect Users After Logout](https://auth0.com/docs/authenticate/login/logout/redirect-users-after-logout)

It's true you have to configure the allowed urls, but that's explained in the Allowed Login URLs section of Application Settings, which again promises a `returnTo` parameter:

> A set of URLs that are valid to redirect to after logout from Auth0. After a user logs out from Auth0 you can redirect them with the returnTo query parameter. 

The environment variable solution, if I understand it right, only supports a single redirect for all logouts. But it's not hard to think of cases where you'd want to send users to different places after logout, depending on what kind of user they are, or where they logged out from, or some other criteria.

For example I needed a "change user" button that logs the user out, lets them sign in to a different account, and brings them back to the page they came from, ie

`/api/auth/logout?returnTo=/api/auth/login?returnTo=/where/we/were/before`

I'm now using a homemade `logout` endpoint that supports `returnTo`, similar to the OP's. But I spent some time being confused & thinking this was a bug before I got there.

Cheers. Thanks for listening.

**Comment by mattdanielmurphy** [comment]
I can confirm the following is confusing:

> Auth0's docs advertise a `logout?returnTo=` parameter, which makes it surprising when `[...auth0].js` turns out not to support it.

**Comment by IonelLupu** [comment]
@adamjmcgrath  @dr-skot @mattdanielmurphy  This is so confusing, yes:
> Auth0's docs advertise a logout?returnTo= parameter, which makes it surprising when [...auth0].js turns out not to support it.

We would like to redirect the user to where it was before logging out and not redirect them to a hardcoded URL.

**Comment by adamjmcgrath** [comment]
> Auth0's docs advertise a logout?returnTo= parameter, which makes it surprising when [...auth0].js turns out not to support it.

As mentioned in https://github.com/auth0/nextjs-auth0/issues/532#issuecomment-966341186 - We do support the `returnTo` parameter. You can either:

- Specify the `routes.postLogoutRedirect` config parameter (or `AUTH0_POST_LOGOUT_REDIRECT` env variable)
- Specify the [returnTo argument](https://auth0.github.io/nextjs-auth0/interfaces/handlers_logout.logoutoptions.html#returnto) when you call the logout handler.

We just don't automatically read this from a parameter on the `/api/auth/logout` url - this is because `returnTo` url's need to be registered in advance with your tenant (this is a security requirement of the protocol, not something this SDK imposes on you). So if we just accepted anything passed through that url, for the most users of this SDK, we'd be creating an API that just sent you to an error page on auth0 in the majority of cases.

If you still want to do this, you can - with a single line of code in your `handleAuth` method:

```js
// pages/api/auth/[...auth0].js
import { handleAuth, handleLogout } from '@auth0/nextjs-auth0';

export default handleAuth({
  logout: handleLogout((req) => ({ returnTo: req.query.returnTo })) // <==
});
```

**Comment by wacanam** [comment]
this is what i did.

```
import { handleAuth, handleLogin, handleLogout, NextAppRouterHandler } from '@auth0/nextjs-auth0';

export const GET: NextAppRouterHandler = async (...args) => {
  const req = args[0];
  const returnTo = req.nextUrl.searchParams.get('returnTo')
  return handleAuth({
    signup: handleLogin({
      authorizationParams: {
        login_hint: 'signup',
      }
    }),
    logout: handleLogout({
      ...returnTo ? { returnTo } : {},
    }),
  })(...args);
}
```
