### ISSUE TITLE
Can no longer check if an error is instance of AccessTokenError

### ISSUE THREAD

**Issue by iliketomatoes** [auth0/nextjs-auth0#535]
### Description

Using the [instanceof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) operator against the `AccessTokenError` constructor always returns false, even if the object that is being tested is actually an instance of `AccessTokenError`.

This is an issue introduced by `nextjs-auth0` **v1.5.0**.

### Reproduction

With `nextjs-auth0` **v1.4.2** I'm able to check if an error occurred inside a NextJS API handler is an instance of `AccessTokenError` by doing so:

```jsx
import { getAccessToken } from '@auth0/nextjs-auth0';
import { AccessTokenError } from '@auth0/nextjs-auth0/dist/utils/errors';
import { ApiError } from 'src/lib/apiClient';

try {
	const tokenInfo = await getAccessToken(req, res);

        // ...

} catch (err: any) {

         // Re-throw an API error in a more convenient format
	throw new ApiError({

                 // Decide what status to return depending on the type of exception that was thrown
		status: err instanceof AccessTokenError ? 401 : 500,
		message: `Code: ${err?.code}, Message: ${err?.message}.`,
	});
}
```

With `nextjs-auth0` **v1.5.0**, I always get a 500 error because errors thrown by `getAccessToken` are always an instance of `Error`, instead `AccessTokenError`.

At least, this is the reason why our unit test on that API endpoint handler is currently failing.

### Environment

- **Library version: v1.5.0**
- **Platform: macOS Big Sur**
- **Languages: Node v14.15.4, TS 4.4.4 (target ES6)**
- **Other modules/plugins/libraries that might be involved: Jest 26.6.3**

**Comment by adamjmcgrath** [comment]
Thanks for raising this @iliketomatoes 

Looks like this was caused by https://github.com/microsoft/TypeScript/issues/13965 when we downgraded the compilation target to `es5` to support IE11 in https://github.com/auth0/nextjs-auth0/commit/c248efe2488b9884d6ab4c88c12b00aa67fe99f7#diff-3ae20d611c1c7263a9c1bce0449291ebfea1c5d578b3fcdbb596353ad885db25R19

There's a workaround here https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work so I'll take a look at fixing it when I can
