### ISSUE TITLE
Support for embedded passwordless login via serverless functions

### ISSUE THREAD

**Issue by Izhaki** [auth0/nextjs-auth0#539]
#### The Goal 

Implement embedded passwordless login, with serverless functions handling authentication.

#### Scope 

- The only case in question here is that of email code (no callbacks or email link involved).
- This is a static nextjs deployment with serverless api functions (no server).
- Web only.

#### What we've done so far

- When the user needs to login, the ui prompts the user for an email.
- When submitted, we call `pages/api/sendEmailCode`. This function calls the auth0 api directly, as described in [Embedded Passwordless Login in Regular Web Applications](https://auth0.com/docs/connections/passwordless/embedded-login/webapps).
- We then prompt the user for the code sent.
- When submitted, we call `pages/api/verifyEmailCode` (as described in [Embedded Passwordless Login in Regular Web Applications](https://auth0.com/docs/connections/passwordless/embedded-login/webapps)).
- We get `access_token` and `id_token`.

Now what? My understanding is that at this point some session should be created and returned with the response (of `verifyEmailCode`); but the library does not seem to offer such functionality.

Ultimately we want to end up in the same place as if we have done the authentication using universal login (which redirects to auth0 for the login prompt). 

### Describe the ideal solution

I admit that I'm not an expert on anything auth related, but am I wrong to suggest something like:

```js
setSession(res, options)
```

Where `options` include all that is needed to create a session?

### Related

https://github.com/auth0/nextjs-auth0/issues/525 - but not sure how related this is and is yet to be resolved (@adamjmcgrath).

https://github.com/auth0/nextjs-auth0/issues/27 - this includes client-side implementation, we are seeking a serverless function solution.

**Comment by adamjmcgrath** [comment]
Hi @Izhaki - thanks for your suggestion

As described in #27 - This SDK only supports Passwordless through the Universal Login Page, not embedded Passwordless, and we have no plans to add support for it I'm afraid.

**Comment by Izhaki** [comment]
Any pointers on how this might be done? The library already offers various session functions, so isn't this a case of stitching existing functionality?

Is there some extraordinary complexity involved in this that should put me off researching it further or attempting this myself?

**Comment by adamjmcgrath** [comment]
I'm not sure exactly how you'd do this but following the [Embedded Passwordless Login in Regular Web Applications](https://auth0.com/docs/connections/passwordless/embedded-login/webapps) docs and using a next session library like [next-session](https://github.com/hoangvvo/next-session) would get you most of the way there.

Passwordless Authentication with Universal Loginis the preferred way to implement Passwordless Authentication (more info https://auth0.com/docs/connections/passwordless/universal-login) which is why we don't have plans to support embedded.

**Comment by sraka1** [comment]
@adamjmcgrath how is this still the preferred way to implement Passwordless Authentication when New Universal Login does not support it at all? This would mean you are actively encouraging clients that need Passwordless to use the "legacy" Classic Universal Login rather than migrating to New Universal Login?
