### ISSUE TITLE
appSession cookie still valid after successful logout

### ISSUE THREAD

**Issue by dtakeshta** [auth0/nextjs-auth0#561]
### Description
I have an issue, and at first I was hesitant to open an issue here, but I don't think this is an actual security vulnerability,  just one we have created for ourselves.

Using burp suite, I'm able to intercept a request and then send that request to the repeater for use later.  I then logout out of the application which calls `/api/auth/logout`.  

We have this in the `api/auth/logout` route:  `await auth0.handleLogout(req, res)`

I have logged into auth0 and checked that the logout request was successful for that user and I see that logged in the history.
`Success Logout`

I am then able to use that `appSession` cookie and continue to send requests to various api routes without getting a 401.  For instance, I have an api route that will update the users information.  I'm able to successfully update this users information while using the `appSession` cookie after I have logged out.   It's as if the session cookie has not been invalidated.

All of our api routes are wrapped with `auth0.withApiAuthRequired`

I don't get exactly what I'm doing wrong, so I'm hoping someone could help point me in the right direction.  If there is any other information that is helpful, please let me know.  I feel like I have provided all relevant information. 

### Reproduction
I'm hoping this can't be reproduced.  

### Environment

> Please provide the following:

- **Version of this library used:** ^1.6.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @dtakeshta - thanks for raising this

This is expected behaviour. The app session cookie is _stateless_. There's no server side state, like a database, to back it up (this is why you didn't have to set up any server side persistence to use the SDK). So you can't revoke or invalidate it. If you're concerned about using a stateless session, you can keep a shorter session expiry using [absoluteDuration](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#absoluteduration) and [rollingDuration](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#rollingduration)

Also, note that we have [custom session stores](https://github.com/auth0/nextjs-auth0/issues/279) in our roadmap, which would add an option to make the session stateful, in our roadmap. Which we'll be looking at early next year.

**Comment by mattcasey** [comment]
Hey @adamjmcgrath, I am having my Next.js app talk to a server built on fastify. I am using `fastify-auth0-verify` to add support for auth0, but it does not ignore the expiration date. So my users can access our pages but the backend considers their tokens invalid after some point in time. Can you offer any guidance on the best approach? My default right now is to just log the user out of the front-end and force them to generate a new token, but it doesn't seem ideal.
I posted an issue with the library because this seems like something that they should support: https://github.com/nearform/fastify-auth0-verify/issues/189.

**Comment by adamjmcgrath** [comment]
Hi @mattcasey 

It's not unusual that your session expiration is longer than your Access Token expiration (Auth0's defaults are 30 days and 1 day respectively)

You have 2 choices:

1. Use Refresh Tokens, so when your Access Token expires you get a new one. So the user can continue to access the backend as long as they have an active session with a refresh token.
2. As you suggest, force the user's session to only last as long as their Access Token and log them out (or prompt them to login again) when you get a 401 from the backend.

**Comment by quanndh** [comment]
> rollingDuration
Hi @adamjmcgrath, I agree session is stateless and available after logout. However, when I sent that link to other people the session live on their end too. They see my account logged in. I just dont know why it happened.
