### ISSUE TITLE
Error on login page when no redirect_uri is provided, origin is undefined

### ISSUE THREAD

**Issue by farmstrong8** [auth0/nextjs-auth0#587]
### Description

Doing a the basic setup errors out when no redirect_uri is provided.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

Here is a screenshot of what happens when routed to the universal login page

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/5731669/152218517-73edf7bd-bd79-444c-82c3-86d830532cad.png">

Code:

```jsx
// pages/api/auth/[...auth0].ts

import { handleAuth } from '@auth0/nextjs-auth0';

export default handleAuth();

```

Working Fix:

when the redirect_uri is set explicitly to one of the options in the list it works (which makes sense) but is there a way to default to the origin of the request? When console logging it looks like `req.headers.origin` is undefined, and `req,headers.host` = "localhost:3000"

```jsx
// pages/api/auth/[...auth0].ts

import { handleAuth, handleLogin } from '@auth0/nextjs-auth0';
import { NextApiRequest, NextApiResponse } from 'next';

export default handleAuth({
  async login(req: NextApiRequest, res: NextApiResponse) {
    try {
      await handleLogin(req, res, {
        authorizationParams: {
          redirect_uri: "http://localhost:3000",
        },
      });
    } catch (e) {
      res.status(400).end(e.message);
    }
  },
});
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.7.0
- **Version of the platform or framework used, if applicable:** next 12.0.9
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @farmstrong8 - thanks for raising this

You should not need to specify a `redirect_uri` - you must specify an `AUTH0_BASE_URL` and the `redirect_uri` will become `$AUTH0_BASE_URL/api/auth/callback`.

Per the [Auth0 Configuration docs](https://github.com/auth0/nextjs-auth0#auth0-configuration) - you also need to register the callback url as an "Allowed Callback URL". So if your `AUTH0_BASE_URL` is `http://localhost:3000` you should register `http://localhost:3000/api/auth/callback` as an Allowed Callback URL.

The "Callback URL Mismatch" error you're seeing is probably because you haven't registered the callback url you are using.

You can confirm this by clicking the `See details for this error` button on your error page, which should say something like `unauthorized_client: Callback URL mismatch. http://localhost:3000/api/auth/callback is not in the list of allowed callback URLs`

**Comment by Widcket** [comment]
@farmstrong8 seems like the above answers your question. I'll close this issue, please ping if you'd prefer to reopen.
