### ISSUE TITLE
`/api/auth/me` keeps returning email_verified=false even after the email is verified

### ISSUE THREAD

**Issue by kenkoooo** [auth0/nextjs-auth0#598]
### Description

`/api/auth/me` keeps returning `email_verified=false` even after the email is verified.

### Reproduction

1. `/api/auth/me` returns `email_verified=false` just after registered to Auth0. The email is not verified, so it's expected behavior.
2. `/api/auth/me` still returns `email_verified=false` after the email is verified. 
3. `/api/auth/me` returns `email_verified=true` after clearing cookies.

### Environment

- @auth0/nextjs-auth0 1.7.0
- next 12.0.10

### Questions

Does it store the user info in the session cookie?

**Comment by adamjmcgrath** [comment]
Hi @kenkoooo - thanks for raising this

This is expected behaviour - `/api/auth/me` returns your userinfo from your cookie session. If you want to fetch new data, you need to use the `refetch` option of `handleProfile` https://auth0.github.io/nextjs-auth0/modules/handlers_profile.html#profileoptions

In order to use the refetch option you need to write a custom profile handler https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior

**Comment by kenkoooo** [comment]
Got it. Thank you for handling this!
