### ISSUE TITLE
add ability to check JWT claims in withPageAuthRequired

### ISSUE THREAD

**Issue by beingtmk** [auth0/nextjs-auth0#628]
### Describe the problem you'd like to have solved
I wanted to easily protect a route not only for logged-in users, but also for those with a given ROLE JWT claim. I figured I'd send this PR in for review in case this team was interested in merging the changes, or some version of them.

### Describe the ideal solution
https://github.com/auth0/auth0-react/pull/211

## Alternatives and current work-arounds
https://github.com/auth0/auth0-react/pull/211

### Additional information, if any
https://github.com/auth0/auth0-react/pull/211

**Comment by adamjmcgrath** [comment]
Hi @beingtmk - if you have a claim check which is unlikely to change by logging the user in again, like checking a role, then `withPageAuthRequired` is probably not for you, since it returns you to the original url after you've logged in - which redirects you to login if you don't have the correct role, causing an infinite loop.

For this case, I would recommend you create your own HOC, which redirects the user to another location, see https://github.com/auth0/auth0-react/issues/320#issuecomment-1013052056 for a react example

**Comment by beingtmk** [comment]
Got it. Thankyou. Did exactly that

**Comment by adamjmcgrath** [comment]
Great 👍
