### ISSUE TITLE
withApiAuthRequired extremely slow

### ISSUE THREAD

**Issue by rgathmann** [auth0/nextjs-auth0#751]
### Description

To simplify this problem, I have created an extremely simple NextJs api endpoint which only returns a string. Unprotected this endpoint will have an average response time of 15ms. However, when I wrap this function with withApiAuthRequired, the response time randomly slows to around 4s on the call with a few short 15ms calls following the first call. However, if you wait around 20-30 seconds, the response time will slow again to around 4s.

### Reproduction

```
async function todos(req, res) {
  return res.status(200).json('success');
}

// This call is switches between slow (~4s) and normal (~15ms)
// export default withApiAuthRequired(todos);

// This call is always fast at ~15ms
export default todos;
```

### Environment

- **Version of this library used: 1.9.1**

**Comment by peec** [comment]
Also experiencing this. Sometimes I even counted 7sec delay. Not locally, only in production. We host the front end on vercel. I am not sure what causes this problem, could it be that apis run on the edge, and these sessions in this library are cached in memory in a hashmap? There is also the cold starts for edge functions.

**Comment by adamjmcgrath** [comment]
Hi @rgathmann - thanks for raising this

I've taken your example code and deployed it to 2 handlers on Vercel at https://vercel-deploy-test-app.vercel.app (using next@latest and auth0/nextjs-auth0@latest)

- `/api/todos` https://github.com/adamjmcgrath/vercel-deploy-test-app/blob/main/pages/api/todos.js
- `/api/todos-with-auth` https://github.com/adamjmcgrath/vercel-deploy-test-app/blob/main/pages/api/todos-with-auth.js

I've not been able to reproduce what you're seeing using the steps you suggested. This is expected since there's no specific caching for this method that should make one request behave differently from the other (the sessions are per request)

I managed to get one request to take >1s which was probably a cold start, and this was the handler that was not wrapped in `withApiAuthRequired`

I suspect what you're seeing is cold starts, the Vercel docs suggest you can see [additional latency of 3 - 5 seconds](https://vercel.com/support/articles/how-can-i-improve-serverless-function-lambda-cold-start-performance-on-vercel#:~:text=If%20you%20have%20large%20dependencies%2C%20parsing%20and%20evaluating%20JavaScript%20code%20can%20take%203%2D5%20seconds%20or%20longer.) for projects that have large dependencies.

![image](https://user-images.githubusercontent.com/1299658/178534344-5d68b7ce-b0b7-4b66-aac8-06977340c0b8.png)

**Comment by rgathmann** [comment]
Strange, maybe what I am experiencing is only on local machines then? Maybe its something to do with my dev environment locally. Appreciate you trying this out.

**Comment by harrycollin** [comment]
I have problems with this in production environments. Deployed to Vercel as well :/

**Comment by jazarja** [comment]
I am experiencing a similar situation where I have two cloud functions—one with Auth0 integration and the other without. The cloud function that incorporates Auth0 seems to have a noticeable delay or slower performance compared to the one without Auth0. Is it possible that the problem is related to a specific region? (deployed on Vercel - Singapore region).
