### ISSUE TITLE
Bundle size, tslib.

### ISSUE THREAD

**Issue by olehreznichenko** [auth0/nextjs-auth0#771]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hello 😊 
I checked the bundle size of my app and noticed that nextjs-auth0 imports `tslib` which is half the size of the package.
<img width="915" alt="image" src="https://user-images.githubusercontent.com/11960153/181043295-edccd4d6-f860-49c1-ae2e-4420913f9c39.png">

### Describe the ideal solution

Would it be possible to ship nextjs-auth0 for modern browsers, so the output would be slimmer without helpers like supports spread operator, assign and etc. ?

**Comment by adamjmcgrath** [comment]
Hi @olehreznichenko - thanks for raising this.

We currently have [`importHelpers` set to `true`](https://github.com/auth0/nextjs-auth0/blob/main/tsconfig.json#L8) - this imports all the helpers that TS provides at runtime in a separate package. The advantage of this is that, if other packages use `importHelpers`, they will not duplicate the helpers this package is using. And according to the [tslib repo](https://github.com/Microsoft/tslib#tslib):

> Because this can avoid duplicate declarations of things like __extends, __assign, etc., this means delivering users smaller files on average, as well as less runtime overhead.

In your case, because we are the only package using `importHelpers` in your project, that 2.6kb (Gzipped) tslib dependency is recognized by `nextjs-auth0`.

If we were to disable `importHelpers` - most of those helpers would be bundled with our package instead, increasing the size of that and not getting the benefits described earlier.

> Would it be possible to ship nextjs-auth0 for modern browsers

The size of the `tslib` is not affected by how you configure the target in tsconfig.

**Comment by Widcket** [comment]
Looks like the above answers your question, so I'll close this issue. Please feel free to ping if you'd prefer to repen.
