### ISSUE TITLE
Can't build on docker.

### ISSUE THREAD

**Issue by jey3dayo** [auth0/nextjs-auth0#86]
### Description
When doing a docker build, an error occurs because there is no environment variable in the `next build`.
I want to `next build` without env.

```Dockerfile
# Dockerfile
FROM node:12.15-alpine

WORKDIR /usr/src/app
COPY package.json .
COPY yarn.lock .
RUN yarn

COPY . .

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
```

```
Automatically optimizing pages...
> Build error occurred
Error: A valid Auth0 Domain must be provided
    at Object.createInstance [as default] (/usr/src/app/node_modules/@auth0/nextjs-auth0/dist/instance.node.js:10:15)
    at initAuth0 (/usr/src/app/node_modules/@auth0/nextjs-auth0/dist/index.js:8:46)
    at Object.xMDF (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:781:127)
    at __webpack_require__ (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:23:31)
    at Module.1TCz (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:147:13)
    at __webpack_require__ (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:23:31)
    at Object.0 (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:99:18)
    at __webpack_require__ (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:23:31)
    at /usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:91:18
    at Object.<anonymous> (/usr/src/app/.next/server/static/GDDYxjIWKG2mlWWc4bTrE/pages/_app.js:94:10)
error Command failed with exit code 1
```

### Environment

- node@v12.15.0
- @auth0/nextjs-auth0@0.10.0
- next@9.2.2

**Comment by huang47** [comment]
when I do `next build` it works for me, however, when I tried to deploy to zeit.co (through `now`) which ends up seeing this error.

**Comment by huang47** [comment]
I used env variables via process.env and when use `now` it doesn't take .env into account even with dotenv-cli. hardcode it in initAuth0 which works for me tho

**Comment by huang47** [comment]
https://zeit.co/docs/v2/build-step#using-environment-variables-and-secrets 

environment variables for build time needs `now.json` plus `now secretes` once you have those configured in docker file it should work fine

**Comment by tomclark** [comment]
I recently encountered this problem too. I'm deploying to a bare metal Kubernetes cluster, not Zeit/Vercel, so I don't have the option of creating environment variables there (if I understand @huang47 correctly). I cheated and created a .env.staging file which I copy to .env as part of my Docker build for my staging environment. When I get to production, I'll need a .env.production, meaning I end up with Docker images for staging and production. Not ideal, but it solves the immediate problem.

**Comment by tomclark** [comment]
I've noticed something that may be useful. I'm deploying to a Kubernetes cluster, and as long as the relevant environment variables are present and correct in the application deployment, they'll override whatever was in the .env file used during the build. So, you can just copy your dev .env file into the Docker build to get you through the build stage without the error, and then when you run the image, the environment variables set in the environment will take precedence.

My Dockerfile looks like this:

```Dockerfile
FROM node:14.4.0-stretch as builder

WORKDIR /app

COPY src .
COPY next.config.js .
COPY package.json .
COPY .env.template .env

RUN yarn install
RUN yarn build

FROM node:14.4.0-stretch
WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
```

My .env.template file looks like this:

```
AUTH0_DOMAIN=domain.eu.auth0.com
AUTH0_CLIENT_ID=auth0clientidauth0clientidauth0c
AUTH0_CLIENT_SECRET=abcdefghilklmnopqrstuvwxyz123456790abdefghijklmnopqrstuvwxyz0123
AUTH0_SCOPE=scopes
AUTH0_AUDIENCE=https://api
REDIRECT_URI=https://site/api/callback
POST_LOGOUT_REDIRECT_URI=https://site/logout
SESSION_COOKIE_SECRET=abcdefghilklmnopqrstuvwxyz123456790abdefghijklmnopqrstuvwxyz012
SESSION_COOKIE_LIFETIME=86400
```

And I mean actually like that. Those aren't dummy values for the purpose of posting on Github - that's what's actually in the file (and it's checked into source control so my CI build just works as well). The point is that it gets through the Docker build. These values will never be actually used because they'll all be set in the environment (and actually, if they're not set, the app won't work and won't pass smoke tests so will alert me to missing values).

My Kubernetes deployment looks something like this:

```yaml
spec:
    containers:
        - image: registry.gitlab.com/myaccount/myproject/mynextclient:latest
          imagePullPolicy: Always
          name: web-client
          ports:
            - containerPort: 3000
          env:
            - name: AUTH0_CLIENT_ID
              value: 'l2wMlA2sxAs697kaZ1pWkpA5UHODwsNj'
            - name: AUTH0_DOMAIN
              value: 'mydomain.eu.auth0.com'
```

In this example, mydomain.eu.auth0.com is a dummy value for posting this answer. The actual value is my Auth0 domain. If you're running the image through Docker, I assume you could just pas the correct environment variables through the command line, or in the environment section of a Compose file.

I expect there's a more correct way of doing this, but it works for my purposes. I hope it's of some help.

**Comment by T00114** [comment]
The way I used the dummy env is a good idea.
I was able to build it with docker-compose.
Thank you for the information.

**Comment by pedropiloto** [comment]
I found a solution that worked for my case (I'm deploying it using caprover). Add the build and the start to the dockerfile CMD:

`CMD bash -c "yarn build && yarn start"`

**Comment by jey3dayo** [comment]
I think this looks good.

https://github.com/auth0/nextjs-auth0/issues/154#issuecomment-677458794

**Comment by Widcket** [comment]
Hi everyone, as a heads up in the new [v1.0.0-beta.0](https://github.com/auth0/nextjs-auth0/releases/tag/v1.0.0-beta.0) by default there's no need to create an SDK instance anymore. The SDK will create a singleton instance and configure itself, provided the required environment variables are set. However, if you need to create an instance you can still do so as well.
Check out more details in the [beta README](https://github.com/auth0/nextjs-auth0/tree/beta#basic-setup) and the [migration guide](https://github.com/auth0/nextjs-auth0/blob/beta/V1_MIGRATION_GUIDE.md).

**Comment by adamjmcgrath** [comment]
Closing this in favour of #154 - see https://github.com/auth0/nextjs-auth0/issues/154#issuecomment-763536833

**Comment by aimproxy** [comment]
@tomclark How do your exactly set the AUTH0_BASE_URL under your k8s deployment?
