### ISSUE TITLE
Logout before receiving network response fails

### ISSUE THREAD

**Issue by k-1ee** [auth0/nextjs-auth0#907]
### Checklist

- [x] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Encountering a consistent issue with logging out when authenticated API calls are pending (response has not been received) before logging out. By authenticated API calls, I'm referring to a request in which a bearer token is included in the header. 

If a user logs out when all network requests have resolved beforehand, everything works as expected - the user session is cleared, there are no session cookies, user must login again. However, if the user logs out before all network requests resolve, it fails every time. The result is that the user's session is still valid ("appSession" cookies are still present after being redirected from Auth0 logout route) even though Auth0 logs a successful logout. 

Had no luck with any solutions posted online, but there is a 1:1 correlation between logouts failing to invalidate the session/remove session cookies and network requests that are pending when logout handler (/api/auth/logout) is finished. This is evident by checking the network tab and seeing that if logout resolves _before_ a particular API response is received, it fails; whereas, logging out _after_ all API responses are received is successful. 

To better understand this issue, could someone provide insight into when a logout would fail to clear the session? At a high level, the issue can be summed up as "sometimes logout works, other times it doesn't."

### Reproduction

1. Make an API call that requires authorization headers
2. Invoke logout handler (/api/auth/logout) before request above is resolved

### SDK version

^1.9.2

### Next.js version

^13.0.0

### Node.js version

16.13.0

**Comment by adamjmcgrath** [comment]
Hi @k-1ee - thanks for raising this

This looks like the result of having a stateless session - if you logout and clear the user agent's cookies, but a concurrent request shows up later with a valid cookie then it will authenticate the request, it has no state to tell it otherwise.

This is also exacerbated by the fact that, since the session is a rolling session, the cookie expiry get's updated on every request. So a concurrent request will write a new cookie after the logout request has deleted it.

If you try the beta (`npm i @auth0/nextjs-auth0@beta`) and disable the rolling session, this will be less likely to happen (since less requests will write to the cookie)

We also, plan to implement stateful sessions in #279 which would prevent this from happening as the cookie correlates the session to state on the server, which the logout request would remove - we hope to begin work on it shortly.

Closing in favour of #279 - but if you have any other questions or want to reopen this, feel free to ping me
