### ISSUE TITLE
Handle refresh token in production app, best practices?

### ISSUE THREAD

**Issue by olaj** [auth0/nextjs-auth0#959]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm experimenting with auto refreshing my access token in an app and i'm wondering if there is any best practices on how to handle it in a good way.

I have for example a dashboard startpage that makes likes 50 requests or so to an API. If the token has expired it seems all my requests is trying to refresh the token at the same time and at least in my dev tenant i get ratelimits and lots of errors, i also need to manually refresh to page after a while to make it work.

### Describe the ideal solution

It would be nice with a more advanced "kitchen sink example" with more real life / complex scenarios and recomended implementations for various stuff like this?

### Alternatives and current workarounds

I'm not really sure how to solve it really, maybe i need to check if the access token is expired manually in the middleware or something and make sure i block everything until the accesstoken is fresh again? Not 100% sure how to do that though :)

### Additional context

Ps. Have you thought about starting a "discussion" section in this repo? It feels a bit wrong to post this stuff as feature requests and posting it to the auth0 community is kind of like throwing it into a black hole :)

**Comment by adamjmcgrath** [comment]
Hey @olaj - thanks for raising this

> I have for example a dashboard startpage that makes likes 50 requests or so to an API. 

This is tricky, because there's no easy way for the SDK, or the application, to manage state between concurrent requests without some sort of state on the server that can be shared between requests. And this SDK, doesn't offer any sort of state like this - the session is a stateless cookie, and even if it did - it would be difficult to manage.

My general suggestion in your case would be to try and reduce the number of API calls when your application starts, perhaps by batching them. It's not an issue if a few requests occasionally concurrently refresh the access token, but as you've seen it can be when the number of requests get's large.

> It would be nice with a more advanced "kitchen sink example" with more real life / complex scenarios and recomended implementations for various stuff like this?

The kitchen sink example covers every feature of the SDK, but can't cover every possible architecture scenario

> Have you thought about starting a "discussion" section in this repo?

Yes, we're happy with the current setup - but this is always under review, so thanks for the feedback

**Comment by olaj** [comment]
Thanks @adamjmcgrath 

Now that i know this is something i have to solve myself it feels so much better to well, solve it myself :)
