### ISSUE TITLE
Vercel caching not working when using this SDK

### ISSUE THREAD

**Issue by PSoltes** [auth0/nextjs-auth0#965]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Using `await getSession(req, res)` in Nextjs API handlers invalidates Vercel caching.
Example repo provided [here](https://github.com/PSoltes/cache-problem-poc).

https://user-images.githubusercontent.com/22454458/207098530-5ad8bdf1-0794-4e51-8c0d-e906d799ce64.mp4

### Reproduction

1. Initialize auth0 through `initAuth0`
2. Create two API routes with identical handlers
3. Use `await getSession(req, res)` in one of them
4. Add correct Cache-Control headers in both of them eg. `res.setHeader('Cache-Control', 'max-age=0, public, s-maxage=3600, stale-while-revalidate=43200')`
5. Deploy on Vercel
6. Call one API route twice, call other API route twice. One api returns `X-Vercel-Cache` as `MISS` then `HIT`, other is `MISS`, `MISS`

### SDK version

2.0.0

### Next.js version

12.3.3

### Node.js version

16.18.0

**Comment by adamjmcgrath** [comment]
Hi @PSoltes - thanks for raising this

Firstly, the cache-control response header in your screen recording is `max-age=0, public` - so I'm not sure if your `res.setHeader` is working.

Secondly, your request to `/with-get-session` is setting the session cookie (it's a rolling session by default so it has to update the cookie expiry) - so you shouldn't want to store it in a shared cache, because if another user hits that shared cache, they'll get your session.

![image](https://user-images.githubusercontent.com/1299658/207105808-8d053cd3-9661-40b0-b49e-10fe31d21cc9.png)

**Comment by PSoltes** [comment]
Yeah, setting header is working, it is just Vercel strips them on a way to client. I've actually implemented our own caching in Redis, and was too doing it per user. Sometimes you focus so hard on why it is not doing something without thinking, that maybe it shouldn't. Do you do anything explicit to prevent caching of these (except set-cookie, cause that doesn't happen with redis version and it still isn't cached)? Anyway thanks for answer, this can be closed/deleted. Keep up good work.

**Comment by adamjmcgrath** [comment]
> Do you do anything explicit to prevent caching of these (except set-cookie, cause that doesn't happen with redis version and it still isn't cached)?

We don't do anything to prevent caching of those (we thought about it, but went for a [note in the docs](https://github.com/auth0/nextjs-auth0/blob/main/SECURITY.md#caching-and-security) instead)

Vercel [don't say they prevent caching](https://vercel.com/docs/concepts/functions/serverless-functions/edge-caching#what-is-cached) on requests with a Set-Cookie header . But it's possible they've updated this behaviour since AWS, Azure and GCP all treat requests with Set-Cookie headers differently when it comes to caching.

> Anyway thanks for answer, this can be closed/deleted. Keep up good work.

Thank you 🙇
